# Generated by Django 3.2 on 2021-05-08 08:04

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=apps.accounts.models.upload_profile_pic),
        ),
    ]
