# Generated by Django 3.2 on 2021-04-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='name',
        ),
    ]
