# Generated by Django 3.2 on 2021-05-08 08:04

import apps.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=apps.photos.models.upload_photo),
            preserve_default=False,
        ),
    ]
